spring:
  application:
    name: Testing_Laboratory
  liquibase:
    enabled: false
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    url: jdbc:postgresql://localhost:49153/postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
